### ISSUE TITLE
Monty Hall 작성

### ISSUE THREAD

**Issue by H-sooyeon** [JNU-FE7-Fellows/montyhall#1]
Monty Hall 알고리즘을 작성하고자 합니다.

## Tasks

- [x] 랜덤으로 스포츠카 넣기
- [x] 사용자가 기존의 문을 선택하는지 / 옮기는지 확인
- [x] 옮긴/기존 문에 대한 확률 출력

## Reference

- [Month Hall_wikipedia](https://en.wikipedia.org/wiki/Monty_Hall_problem)
