### ISSUE TITLE
Monty hall 실습 검토 방안 CheckList

### ISSUE THREAD

**Issue by DongHwaKwon** [JNU-FE7-Fellows/montyhall#3]
## Description

Monty hall 실습 검토 방안을 작성하고자 합니다.
 
## Tasks

- [x] 난수의 seed값이 초기화 되는가?
- [x] 자료형이 동등한 확률의 난수 생성을 위하여 적합한가?
- [x] 이론값과 결과값이 동일한가?
- [x] 유의미한 반복을 진행하였는가?

## Reference

- [참조 블로그](https://coding-factory.tistory.com/666)
